SELECT * FROM SCHEDULE_BASIC sb ;

SELECT * FROM SCHEDULE s ;

DELETE  FROM SCHEDULE;

DELETE  FROM SCHEDULE_BASIC sb ;

ALTER TABLE WORKSPACE MODIFY(WS_IP VARCHAR2(20);

SELECT * FROM WORKSPACE w ;

SELECT SCH_SCHEDULE FROM SCHEDULE s WHERE SCH_MONTH ='2020-06' AND WS_CODE='200618employer';

SELECT SCH_REVISEABLE FROM SCHEDULE s WHERE SCH_MONTH ='2020-06' AND WS_CODE='200618employer';

SELECT u.USER_ID||' '||WS_CODE||' '||u.USER_NAME MEMBERINFO 
FROM EMPLOYEE e,USERINFO u 
WHERE u.USER_ID =e.USER_ID AND WS_CODE ='200618employer' AND EMP_RANK ='emp';

SELECT * FROM USERINFO u ;



INSERT INTO SC.SCHEDULE
(SCH_CODE, WS_CODE, SCH_MONTH, SCH_SCHEDULE, SCH_REVISEABLE)
VALUES(SCHEDULE_SEQ.NEXTVAL,'200619employer','2020-06','인서트해보자', 'D');

DELETE  FROM SCHEDULE s WHERE SCH_SCHEDULE='업데이트해보자';
SELECT * FROM SCHEDULE s ;
SELECT * FROM SCHEDULE_BASIC sb ;


UPDATE SCHEDULE SET SCH_SCHEDULE ='업데이트해보자' WHERE SCH_MONTH ='2020-06' AND WS_CODE='200619employer';
SELECT * FROM WORKSPACE w ;

UPDATE WORKSPACE SET WS_DELFLAG ='N' WHERE WS_CODE ='200618employer';

SELECT * FROM EMPLOYEE e ;

DELETE FROM EMPLOYEE e WHERE EMP_CODE ='2020061834'


DELETE FROM SCHEDULE s ;

SELECT * FROM SCHEDULE s ;

DELETE FROM SCHEDULE s WHERE WS_CODE ='200618employer' AND SCH_MONTH ='2020-06';